<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="ROBOTS" content="NOINDEX,NOFOLLOW,NOARCHIVE" />
	<link rel="shortcut icon" href="/practPython/image/favicon.ico" type="image/x-icon" />
	<link rel="stylesheet" href="/practPython/style/main.css" />
	<link rel="stylesheet" href="/practPython/style/modal.css" />
	<title>Редактирование таблицы на Python, JavaScript</title>
</head>
<body>
    <div class="center"></div>
	<h1><a href=".">Редактирование таблицы на Python, JavaScript (на основе HTML 5, CSS 3.0)</a></h1>
</body>
</html>